#!/bin/bash

g++ -g -Wall -Werror -std=c++17 ./*.cpp ./test/*.cpp -o ../bin/client -lstdc++fs
valgrind --leak-check=full --show-leak-kinds=all ../bin/client

if [ "$1" == "-r" ]
then
rm ../bin/client
#rm ./--library=stdc++fs
fi