version: '3.1'
services: 
    server:
        build: ./server
        ports: 
            - "3500:3500"
    client:
        build: ./client
        ports: 
            - "2800:2800"
    mongodb:
        image: mongo
        container_name: mongo
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./db:/data/db
        ports:
            - 27018:27017
        command: mongod --logpath=/dev/null # --quiet
