version: '3.1'
services: 
    server:
        build: ./server
        ports: 
            - "3500:3500"
        #volumes: 
            #- ./server/src:/home/src
            #- ./server/bin:/home/bin
        #working_dir: /home/src
        #stdin_open: true
        #tty: true
    client:
        build: ./client
        ports: 
            - "2800:2800"
        #volumes: 
            #- ./client/src:/home/src
            #- ./client/bin:/home/bin
        #working_dir: /home/src
        #stdin_open: true
        #tty: true
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example