version: '3.1'
services: 
    server:
        build: ./server
        ports: 
            - "3500:3500"
    load-balancer:
        build: ./load-balancer
        ports:
            - "3100:3100"
    client:
        build: ./client
        ports: 
            - "2800:2800"
    db-attivo:
        build: ./db-attivo
        ports: 
            - "3305:3306"
    db-passivo:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        #volumes: 
            #- ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: example
