version: '3.1'
services: 
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        security_opt:
            - seccomp:unconfined
    server:
        build: ./server
        ports: 
            - "3500:3500"
    load-balancer:
        build: ./load-balancer
        ports:
            - "3100:3100"
    client:
        build: ./client
        ports: 
            - "2800:2800"

