version: '3.1'
services: 
    server:
        build: ./server
        ports: 
            - "3500:3500"
        volumes: 
            - ./server/src
    client:
        build: ./client
        ports: 
            - "2800:2800"
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example