version: '3.1'
services: 
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        security_opt:
            - seccomp:unconfined
    server:
        build: ./server
        ports: 
            - "3500-3503:3500"
        volumes:
            - filesystem:/home/filesystem
    nginx-server:
        image: nginx
        ports:
            - "3200:80"
        volumes: 
            - './server/config/nginx.conf:/etc/nginx/nginx.conf'
    #client:
        #build: ./client
        #ports: 
        #    - "2800:2800"
        #volumes: 
            #- "./client/sync:/home/client/sync"
            #- "./client/config:/home/client/config"
volumes: 
    filesystem:

