# BUILD A NEW IMAGE TO PUSH ON DOCKER HUB
FROM gjcode/gjcode-pds:1.0.6
LABEL author="GJCode"
#COPY ./ /
RUN apt-get update && apt-get install libssl-dev -y

#FROM mysql
#LABEL author="GJCode"
#COPY ./ /home
#WORKDIR /home
# install tools
#RUN apt update \
#    && apt install build-essential -y\
#    && apt install snapd -y \
#    && apt-get install valgrind -y  \
#    && apt-get install libboost-all-dev -y  \
#    && apt install ./libmysqlcppconn7_8.0.21-1debian10_amd64.deb \
#    && apt-get install libmysqlcppconn-dev -y


