#pragma once

enum TOPIC {
    NEW_FILE, 
    NEW_FOLDER, 
    CONTENT_MOVED, 
    FILE_RENAMED, 
    FILE_MODIFIED, 
    FILE_DELETED, 
    FILE_COMPLETED,
    BULK_DELETE, 
    ADD_CHUNK, 
    UPDATE_CHUNK,
    DELETE_CHUNK,
    REMOVE_ENTRY,
    UP_EMPTY,
    DOWN_EMPTY,
    GET_STATUS,
    LIST,
    LOGGED_IN,
    LOGGED_OUT,
    CLOSE,
    TIME_OUT,
    ENTRY_RENAMED
    };